enum DiallingCodes {
  Afghanistan = '93',
  Albania = '355',
  Algeria = '213',
  Andorra = '376',
  Angola = '244',
  Argentina = '54',
  Armenia = '374',
  Australia = '61',
  Austria = '43',
  Azerbaijan = '994',
  Bahamas = '1-242',
  Bahrain = '973',
  Bangladesh = '880',
  Barbados = '1-246',
  Belarus = '375',
  Belgium = '32',
  Belize = '501',
  Benin = '229',
  Bhutan = '975',
  Bolivia = '591',
  BosniaAndHerzegovina = '387',
  Botswana = '267',
  Brazil = '55',
  Brunei = '673',
  Bulgaria = '359',
  BurkinaFaso = '226',
  Burundi = '257',
  Cambodia = '855',
  Cameroon = '237',
  Canada = '1',
  CapeVerde = '238',
  CentralAfricanRepublic = '236',
  Chad = '235',
  Chile = '56',
  China = '86',
  Colombia = '57',
  Comoros = '269',
  Congo = '242',
  CostaRica = '506',
  Croatia = '385',
  Cuba = '53',
  Cyprus = '357',
  CzechRepublic = '420',
  Denmark = '45',
  Djibouti = '253',
  Dominica = '1-767',
  DominicanRepublic = '1-809',
  Ecuador = '593',
  Egypt = '20',
  ElSalvador = '503',
  EquatorialGuinea = '240',
  Eritrea = '291',
  Estonia = '372',
  Eswatini = '268',
  Ethiopia = '251',
  Fiji = '679',
  Finland = '358',
  France = '33',
  Gabon = '241',
  Gambia = '220',
  Georgia = '995',
  Germany = '49',
  Ghana = '233',
  Greece = '30',
  Grenada = '1-473',
  Guatemala = '502',
  Guinea = '224',
  GuineaBissau = '245',
  Guyana = '592',
  Haiti = '509',
  Honduras = '504',
  Hungary = '36',
  Iceland = '354',
  India = '91',
  Indonesia = '62',
  Iran = '98',
  Iraq = '964',
  Ireland = '353',
  Israel = '972',
  Italy = '39',
  Jamaica = '1-876',
  Japan = '81',
  Jordan = '962',
  Kazakhstan = '7',
  Kenya = '254',
  Kiribati = '686',
  Kuwait = '965',
  Kyrgyzstan = '996',
  Laos = '856',
  Latvia = '371',
  Lebanon = '961',
  Lesotho = '266',
  Liberia = '231',
  Libya = '218',
  Liechtenstein = '423',
  Lithuania = '370',
  Luxembourg = '352',
  Madagascar = '261',
  Malawi = '265',
  Malaysia = '60',
  Maldives = '960',
  Mali = '223',
  Malta = '356',
  MarshallIslands = '692',
  Mauritania = '222',
  Mauritius = '230',
  Mexico = '52',
  Micronesia = '691',
  Moldova = '373',
  Monaco = '377',
  Mongolia = '976',
  Montenegro = '382',
  Morocco = '212',
  Mozambique = '258',
  Myanmar = '95',
  Namibia = '264',
  Nauru = '674',
  Nepal = '977',
  Netherlands = '31',
  NewZealand = '64',
  Nicaragua = '505',
  Niger = '227',
  Nigeria = '234',
  NorthKorea = '850',
  NorthMacedonia = '389',
  Norway = '47',
  Oman = '968',
  Pakistan = '92',
  Palau = '680',
  Palestine = '970',
  Panama = '507',
  PapuaNewGuinea = '675',
  Paraguay = '595',
  Peru = '51',
  Philippines = '63',
  Poland = '48',
  Portugal = '351',
  Qatar = '974',
  Romania = '40',
  Russia = '7',
  Rwanda = '250',
  SaintKittsAndNevis = '1-869',
  SaintLucia = '1-758',
  SaintVincentAndTheGrenadines = '1-784',
  Samoa = '685',
  SanMarino = '378',
  SaoTomeAndPrincipe = '239',
  SaudiArabia = '966',
  Senegal = '221',
  Serbia = '381',
  Seychelles = '248',
  SierraLeone = '232',
  Singapore = '65',
  Slovakia = '421',
  Slovenia = '386',
  SolomonIslands = '677',
  Somalia = '252',
  SouthAfrica = '27',
  SouthKorea = '82',
  SouthSudan = '211',
  Spain = '34',
  SriLanka = '94',
  Sudan = '249',
  Suriname = '597',
  Sweden = '46',
  Switzerland = '41',
  Syria = '963',
  Taiwan = '886',
  Tajikistan = '992',
  Tanzania = '255',
  Thailand = '66',
  TimorLeste = '670',
  Togo = '228',
  Tonga = '676',
  TrinidadAndTobago = '1-868',
  Tunisia = '216',
  Turkey = '90',
  Turkmenistan = '993',
  Tuvalu = '688',
  Uganda = '256',
  Ukraine = '380',
  UnitedArabEmirates = '971',
  UnitedKingdom = '44',
  UnitedStates = '1',
  Uruguay = '598',
  Uzbekistan = '998',
  Vanuatu = '678',
  VaticanCity = '379',
  Venezuela = '58',
  Vietnam = '84',
  Yemen = '967',
  Zambia = '260',
  Zimbabwe = '263',
}

const diallingCodesObj = [
  { country: 'Afghanistan', code: '+93' },
  { country: 'Albania', code: '+355' },
  { country: 'Algeria', code: '+213' },
  { country: 'Andorra', code: '+376' },
  { country: 'Angola', code: '+244' },
  { country: 'Argentina', code: '+54' },
  { country: 'Armenia', code: '+374' },
  { country: 'Australia', code: '+61' },
  { country: 'Austria', code: '+43' },
  { country: 'Azerbaijan', code: '+994' },
  { country: 'Bahamas', code: '+1-242' },
  { country: 'Bahrain', code: '+973' },
  { country: 'Bangladesh', code: '+880' },
  { country: 'Barbados', code: '+1-246' },
  { country: 'Belarus', code: '+375' },
  { country: 'Belgium', code: '+32' },
  { country: 'Belize', code: '+501' },
  { country: 'Benin', code: '+229' },
  { country: 'Bhutan', code: '+975' },
  { country: 'Bolivia', code: '+591' },
  { country: 'Bosnia and Herzegovina', code: '+387' },
  { country: 'Botswana', code: '+267' },
  { country: 'Brazil', code: '+55' },
  { country: 'Brunei', code: '+673' },
  { country: 'Bulgaria', code: '+359' },
  { country: 'Burkina Faso', code: '+226' },
  { country: 'Burundi', code: '+257' },
  { country: 'Cambodia', code: '+855' },
  { country: 'Cameroon', code: '+237' },
  { country: 'Canada', code: '+1' },
  { country: 'Cape Verde', code: '+238' },
  { country: 'Central African Republic', code: '+236' },
  { country: 'Chad', code: '+235' },
  { country: 'Chile', code: '+56' },
  { country: 'China', code: '+86' },
  { country: 'Colombia', code: '+57' },
  { country: 'Comoros', code: '+269' },
  { country: 'Congo', code: '+242' },
  { country: 'Costa Rica', code: '+506' },
  { country: 'Croatia', code: '+385' },
  { country: 'Cuba', code: '+53' },
  { country: 'Cyprus', code: '+357' },
  { country: 'Czech Republic', code: '+420' },
  { country: 'Denmark', code: '+45' },
  { country: 'Djibouti', code: '+253' },
  { country: 'Dominica', code: '+1-767' },
  { country: 'Dominican Republic', code: '+1-809' },
  { country: 'Ecuador', code: '+593' },
  { country: 'Egypt', code: '+20' },
  { country: 'El Salvador', code: '+503' },
  { country: 'Equatorial Guinea', code: '+240' },
  { country: 'Eritrea', code: '+291' },
  { country: 'Estonia', code: '+372' },
  { country: 'Eswatini', code: '+268' },
  { country: 'Ethiopia', code: '+251' },
  { country: 'Fiji', code: '+679' },
  { country: 'Finland', code: '+358' },
  { country: 'France', code: '+33' },
  { country: 'Gabon', code: '+241' },
  { country: 'Gambia', code: '+220' },
  { country: 'Georgia', code: '+995' },
  { country: 'Germany', code: '+49' },
  { country: 'Ghana', code: '+233' },
  { country: 'Greece', code: '+30' },
  { country: 'Grenada', code: '+1-473' },
  { country: 'Guatemala', code: '+502' },
  { country: 'Guinea', code: '+224' },
  { country: 'Guinea-Bissau', code: '+245' },
  { country: 'Guyana', code: '+592' },
  { country: 'Haiti', code: '+509' },
  { country: 'Honduras', code: '+504' },
  { country: 'Hungary', code: '+36' },
  { country: 'Iceland', code: '+354' },
  { country: 'India', code: '+91' },
  { country: 'Indonesia', code: '+62' },
  { country: 'Iran', code: '+98' },
  { country: 'Iraq', code: '+964' },
  { country: 'Ireland', code: '+353' },
  { country: 'Israel', code: '+972' },
  { country: 'Italy', code: '+39' },
  { country: 'Jamaica', code: '+1-876' },
  { country: 'Japan', code: '+81' },
  { country: 'Jordan', code: '+962' },
  { country: 'Kazakhstan', code: '+7' },
  { country: 'Kenya', code: '+254' },
  { country: 'Kiribati', code: '+686' },
  { country: 'Kuwait', code: '+965' },
  { country: 'Kyrgyzstan', code: '+996' },
  { country: 'Laos', code: '+856' },
  { country: 'Latvia', code: '+371' },
  { country: 'Lebanon', code: '+961' },
  { country: 'Lesotho', code: '+266' },
  { country: 'Liberia', code: '+231' },
  { country: 'Libya', code: '+218' },
  { country: 'Liechtenstein', code: '+423' },
  { country: 'Lithuania', code: '+370' },
  { country: 'Luxembourg', code: '+352' },
  { country: 'Madagascar', code: '+261' },
  { country: 'Malawi', code: '+265' },
  { country: 'Malaysia', code: '+60' },
  { country: 'Maldives', code: '+960' },
  { country: 'Mali', code: '+223' },
  { country: 'Malta', code: '+356' },
  { country: 'Marshall Islands', code: '+692' },
  { country: 'Mauritania', code: '+222' },
  { country: 'Mauritius', code: '+230' },
  { country: 'Mexico', code: '+52' },
  { country: 'Micronesia', code: '+691' },
  { country: 'Moldova', code: '+373' },
  { country: 'Monaco', code: '+377' },
  { country: 'Mongolia', code: '+976' },
  { country: 'Montenegro', code: '+382' },
  { country: 'Morocco', code: '+212' },
  { country: 'Mozambique', code: '+258' },
  { country: 'Myanmar', code: '+95' },
  { country: 'Namibia', code: '+264' },
  { country: 'Nauru', code: '+674' },
  { country: 'Nepal', code: '+977' },
  { country: 'Netherlands', code: '+31' },
  { country: 'New Zealand', code: '+64' },
  { country: 'Nicaragua', code: '+505' },
  { country: 'Niger', code: '+227' },
  { country: 'Nigeria', code: '+234' },
  { country: 'North Korea', code: '+850' },
  { country: 'North Macedonia', code: '+389' },
  { country: 'Norway', code: '+47' },
  { country: 'Oman', code: '+968' },
  { country: 'Pakistan', code: '+92' },
  { country: 'Palau', code: '+680' },
  { country: 'Palestine', code: '+970' },
  { country: 'Panama', code: '+507' },
  { country: 'Papua New Guinea', code: '+675' },
  { country: 'Paraguay', code: '+595' },
  { country: 'Peru', code: '+51' },
  { country: 'Philippines', code: '+63' },
  { country: 'Poland', code: '+48' },
  { country: 'Portugal', code: '+351' },
  { country: 'Qatar', code: '+974' },
  { country: 'Romania', code: '+40' },
  { country: 'Russia', code: '+7' },
  { country: 'Rwanda', code: '+250' },
  { country: 'Saint Kitts and Nevis', code: '+1-869' },
  { country: 'Saint Lucia', code: '+1-758' },
  { country: 'Saint Vincent and the Grenadines', code: '+1-784' },
  { country: 'Samoa', code: '+685' },
  { country: 'San Marino', code: '+378' },
  { country: 'Sao Tome and Principe', code: '+239' },
  { country: 'Saudi Arabia', code: '+966' },
  { country: 'Senegal', code: '+221' },
  { country: 'Serbia', code: '+381' },
  { country: 'Seychelles', code: '+248' },
  { country: 'Sierra Leone', code: '+232' },
  { country: 'Singapore', code: '+65' },
  { country: 'Slovakia', code: '+421' },
  { country: 'Slovenia', code: '+386' },
  { country: 'Solomon Islands', code: '+677' },
  { country: 'Somalia', code: '+252' },
  { country: 'South Africa', code: '+27' },
  { country: 'South Korea', code: '+82' },
  { country: 'South Sudan', code: '+211' },
  { country: 'Spain', code: '+34' },
  { country: 'Sri Lanka', code: '+94' },
  { country: 'Sudan', code: '+249' },
  { country: 'Suriname', code: '+597' },
  { country: 'Sweden', code: '+46' },
  { country: 'Switzerland', code: '+41' },
  { country: 'Syria', code: '+963' },
  { country: 'Taiwan', code: '+886' },
  { country: 'Tajikistan', code: '+992' },
  { country: 'Tanzania', code: '+255' },
  { country: 'Thailand', code: '+66' },
  { country: 'Timor-Leste', code: '+670' },
  { country: 'Togo', code: '+228' },
  { country: 'Tonga', code: '+676' },
  { country: 'Trinidad and Tobago', code: '+1-868' },
  { country: 'Tunisia', code: '+216' },
  { country: 'Turkey', code: '+90' },
  { country: 'Turkmenistan', code: '+993' },
  { country: 'Tuvalu', code: '+688' },
  { country: 'Uganda', code: '+256' },
  { country: 'Ukraine', code: '+380' },
  { country: 'United Arab Emirates', code: '+971' },
  { country: 'United Kingdom', code: '+44' },
  { country: 'United States', code: '+1' },
  { country: 'Uruguay', code: '+598' },
  { country: 'Uzbekistan', code: '+998' },
  { country: 'Vanuatu', code: '+678' },
  { country: 'Vatican City', code: '+379' },
  { country: 'Venezuela', code: '+58' },
  { country: 'Vietnam', code: '+84' },
  { country: 'Yemen', code: '+967' },
  { country: 'Zambia', code: '+260' },
  { country: 'Zimbabwe', code: '+263' },
]

export { diallingCodesObj, DiallingCodes }
